###### Content originally from https://github.com/engineersCode/EngComp
##### Licensed under Creative Commons Attribution license CC-BY 4.0, code under BSD 3-Clause License © 2017 L.A. Barba, N.C. Clementi
##### Adapted for Digital Skills course, TU Delft, 2018

NumPy offers many [ways to create arrays](https://docs.scipy.org/doc/numpy/reference/routines.array-creation.html#routines-array-creation). Explore the above link to see just how many.

Play with `numpy.ones()` and `numpy.zeros()`: they acreate arrays full of ones and zeros, respectively. We must tell NumPy how many array elements want:
                                          

In [2]:
import numpy as np
np.ones(5)

array([1., 1., 1., 1., 1.])

In [4]:
np.zeros(3)

array([0., 0., 0.])

Another useful command: `numpy.arange()` gives an array of evenly spaced values in a defined interval. 

*Syntax:*

`numpy.arange(start, stop, step)`

* `start` by default is zero
* `stop` is not inclusive, and 
* the `step` has a default value of 1.

Try it out:


In [6]:
np.arange(4)

# we could have also written, but you will agree that this is unnecesary:
np.arange(start=0, stop=4, step=1)

array([0, 1, 2, 3])

In [7]:
np.arange(start=2, stop=6, step=1)
np.arange(start=2, stop=6)  # leave `step` unspecified
np.arange(2, 6)             # leave the arguments unspecified

array([2, 3, 4, 5])

In [8]:
np.arange(start=2, stop=9, step=2)
np.arange(2, 9, 2)

array([2, 4, 6, 8])

In [9]:
np.arange(2, 6, 0.5)

array([2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5])

`np.linspace()` is similar to `np.arange()`, but uses number of samples instead of a step size. It returns an array with evenly spaced numbers over the specified interval.  

*Syntax:*

`np.linspace(start, stop, num)`

`stop` is included by default (it can be removed, read the docs), and `num` by default is 50. 

In [ ]:
np.linspace(2.0, 3.0)

In [ ]:
len(np.linspace(2.0, 3.0))   # confirm the default length is indeed 50

In [ ]:
np.linspace(start=2.0, stop=3.0, num=6)
np.linspace(2.0, 3.0, 6)     # these 2 lines produce identical results; verify it for yourself

In [ ]:
np.linspace(-1, 1, 9)