All content is under Creative Commons Attribution CC-BY 4.0 and all source code is under BSD-3 clause. Parts of these materials were inspired by https://github.com/engineersCode/EngComp/ (CC-BY 4.0), L.A. Barba, N.C. Clementi

Please reuse, remix, revise, and reshare this content in any way, keeping this notice! 

**Viewing this on jupyter.org?** This is then read-only. To learn how to more effectively interact with this notebook, visit our [instruction page about Notebooks](https://yint.org/notebooks).

# Vectors, Matrices and Arrays using NumPy

Let's quickly get the definitions out of the way, and start:
* **Vector**: a sequence of numbers; very much like a `list` in regular Python: [1, 2, 6, -2, 0].
* **Matrix**: a 2-dimensional structure of numbers; a vector is therefore a matrix, where one of the dimensions is equal to 1. You could crudely store a matrix in regular Python using a list of lists, where the main list contains entries which themselves are lists. But while this could store your data, it would not be great for calculations, such as matrix multiplication.
* **Array**: an n-dimensional structure of numbers; a general form of a matrix, but with multiple dimensions. 

For example, a 3-dimensional array here shows data collected in a lab: we are performing the experiment several times (N), in each experiment we have several sensors (K), and we set the sensors to collect data on a regular interval so that we end up with J samples per experiment, per sensor.


<img src="images/batch-data-layers-into-page-3d-structure.png" style="width: 400px;"/> 

Storing the data like this is useful, because now you could perform calculations on all experiments over all time, for all sensors in array X.

*For example:* you can calculate the average in the direction of arrow $J$, to reduce the *array* to a *matrix*. That matrix would be the average value of the sensor for the experiments. That reduced matrix would have $N$ rows and $K$ columns.

Engineering applications benefit from using *vectors*, or *matrices* or *arrays*: they are sequences of data all of the _same type_. Arrays behave a lot like lists in Python, except for the constraint that all elements have the same type. 



NumPy offers many [ways to create arrays](https://docs.scipy.org/doc/numpy/reference/routines.array-creation.html#routines-array-creation). 


###  To try:
1. Open that link above to see just how many ways there are.
2. Test the `numpy.ones()` and `numpy.zeros()` commands: they create arrays full of ones and zeros, respectively. We must tell NumPy how many array elements want. 
                                          

In [1]:
# To try: change the '5' to some other integer number
import numpy as np
np.ones(5)

array([1., 1., 1., 1., 1.])

In [2]:
# Create a vector of zeros:
np.zeros(3)

array([0., 0., 0.])

## Other ways of creating vectors

Another useful command: `numpy.arange()` gives an array of evenly spaced values in a defined interval. 

*Syntax:*

`numpy.arange(start, stop, step)`

* `start` by default is zero
* `stop` is not inclusive, and 
* the `step` has a default value of 1.

Try it out below:


In [3]:
np.arange(4)

# we could have also written, but you will agree that this is unnecesary:
np.arange(start=0, stop=4, step=1)

array([0, 1, 2, 3])

In [4]:
np.arange(start=2, stop=6, step=1)
np.arange(start=2, stop=6)  # leave `step` unspecified
np.arange(2, 6)             # leave the arguments unspecified

array([2, 3, 4, 5])

In [5]:
np.arange(start=2, stop=9, step=2)
np.arange(2, 9, 2)

array([2, 4, 6, 8])

In [6]:
np.arange(2, 6, 0.5)

array([2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5])

`np.linspace()` is similar to `np.arange()`, but uses number of samples instead of a step size. It returns an array with evenly spaced numbers over the specified interval.  

*Syntax:*

`np.linspace(start, stop, num)`

`stop` is included by default (it can be removed, read the docs), and `num` by default is 50. 

### To try:

1. Confirm that you indeed get a vector of 50 entries with the default command.
2. Try to get a vector with fewer elements, say 6
3. Start from a negative beginning point

In [ ]:
# To try:

# Step 1:
np.linspace(2.0, 3.0)
len(np.linspace(2.0, 3.0))   # confirm the default length is indeed 50

# Step 2:
np.linspace(start=2.0, stop=3.0, num= ...)
np.linspace(2.0, 3.0, ...)     # these lines produce identical results; verify it for yourself

# Step 3:
np.linspace(-1, 1, 9)