<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Creating-your-first-matrix-(a-two-dimensional-array)" data-toc-modified-id="Creating-your-first-matrix-(a-two-dimensional-array)-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Creating your first matrix (a two-dimensional array)</a></span></li><li><span><a href="#Creating-your-first-multi-dimensional-array" data-toc-modified-id="Creating-your-first-multi-dimensional-array-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Creating your first multi-dimensional array</a></span></li><li><span><a href="#Summary" data-toc-modified-id="Summary-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Summary</a></span></li></ul></div>

>All content is released under Creative Commons Attribution [CC-BY 4.0](https://creativecommons.org/licenses/by/4.0/) and all source code is released under a [BSD-3 clause license](https://en.wikipedia.org/wiki/BSD_licenses). Parts of these materials were inspired by https://github.com/engineersCode/EngComp/ (CC-BY 4.0), L.A. Barba, N.C. Clementi.
>
>Please reuse, remix, revise, and reshare this content in any way, keeping this notice. [Report issues please](https://github.com/kgdunn/digital-skills-module5/issues).
>
><img style="float: right;" width="150px" src="images/jupyter-logo.png">**Are you viewing this on jupyter.org?** Then this notebook will be read-only. <br>
>See how you can interactively run the code in this notebook by visiting our [instruction page about Notebooks](https://yint.org/notebooks). 

# Creating vectors, matrices and arrays with NumPy

NumPy offers many [ways to create arrays](https://docs.scipy.org/doc/numpy/reference/routines.array-creation.html#routines-array-creation). 


###  To try below:
> 1. Scroll through that link above to see just how many ways there are.
> 2. One of the simplest vectors we can create is a vector of just 1's. Try the `numpy.ones()` command below. We must tell NumPy how many array elements want. 
                                          

In [1]:
# To try: change the '5' to some other integer number
import numpy as np
np.ones(shape=5)    # complete function call
np.ones(5)          # how it is commonly used

array([1., 1., 1., 1., 1.])

In [2]:
# There is also a command to create a vector of zeros:
np.zeros(shape=3)
np.zeros(3)

array([0., 0., 0.])

## Creating your first matrix (a two-dimensional array)

For this we use the ``.ones()`` or ``.zeros()`` command, but we just specify the ``shape`` differently.

In [3]:
twoD = np.ones(shape=(5,7))
print(twoD)
print(twoD.shape)
print('------------')

naughts = np.zeros((5,7))
print(naughts)
print(type(naughts))      # you have created an object with type `numpy.ndarray`

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]
(5, 7)
------------
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
<class 'numpy.ndarray'>


## Creating your first multi-dimensional array

Why stop at two-dimenions? Create a 3-dimenional array with 2 rows, 3 columns and 4 layers: in other words a $2 \times 3 \times $$ array.

Just adjust the `tuple` provided to the `shape` argument:

In [ ]:
threeD = np.zeros(shape=(2,3,4))
print(threeD)
print(threeD.shape)

# Is this what you expected to see? You might have to imagine the 3rd dimension going in and out of the screen.

### To try below

>1. Try to create a matrix with 4 rows and 5 column where every value in the matrix is the number 8. Do this by making a matrix of only ``.ones()`` and multiplying that matrix by the value of 8.
>2. Now do the same thing, using the ``np.full`` command. If you need help, please see the [Numpy documentation for the ``np.full`` command](https://docs.scipy.org/doc/numpy/reference/generated/numpy.full.html#numpy.full]) .



In [ ]:
# Step 1:
eights = np.ones( ___ ) * ___
print(eights)

In [ ]:
# Step 2:
eight_again = np.full(shape=___, fill_value=___)
print(eight_again)

## Summary

You have created vectors, matrices and arrays. These have a specific ``.shape`` that you can check. 

These objects are of the type ``numpy.ndarray``: an n-dimensional array.