>All content is released under Creative Commons Attribution [CC-BY 4.0](https://creativecommons.org/licenses/by/4.0/) and all source code is released under a [BSD-3 clause license](https://en.wikipedia.org/wiki/BSD_licenses). Parts of these materials were inspired by https://github.com/engineersCode/EngComp/ (CC-BY 4.0), L.A. Barba, N.C. Clementi.
>
>Please reuse, remix, revise, and reshare this content in any way, keeping this notice.
>
><img style="float: right;" width="150px" src="images/jupyter-logo.png">**Are you viewing this on jupyter.org?** Then this notebook will be read-only. <br>
>See how you can interactively run the code in this notebook by visiting our [instruction page about Notebooks](https://yint.org/notebooks). 

# Further ways of creating NumPy arrays

In this section we will look at creating arrays, particularly matrices, in an effecient manner. 

1. Identity matrices: what if you need an [identity matrix](https://en.wikipedia.org/wiki/Identity_matrix) (a matrix with 1's on the diagonal)?
2. Random matrices: arrays filled with random numbers
3. Vector sequences: say you need a vector where the entries are ``[0, 1, 2, 3, 4, ..., 9]``
4. Matrix from a vector: take a vector (of say 12 entries) and reshape it into an array (of 3 rows and 4 columns)

In the next section we will look at these


## 1. Identity matrices

A square matrix with 1's on the diagonal and zeros everywhere else is known as an identity matrix. For example a $4\times 4$ identity matrix is:  $$I_4 = \begin{bmatrix}
1 & 0 & 0 & 0 \\
0 & 1 & 0 & 0 \\
0 & 0 & 1 & 0 \\
0 & 0 & 0 & 1 \end{bmatrix}$$

In [1]:
import numpy as np
np.identity?
id5 = np.identity(n=5)
print(id5)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


A similar function to ``np.identity(...)`` is ``np.eye(...)``. It is a play on words, where ``eye`` refers to the uppercase letter $I$. The above above $4\times 4$ matrix is often written as $I_4$ in mathematical notation.

In [2]:
# Try the following, to see what they produce:

also_id5 = np.eye(5)
print(also_id5)
print('-----')

yet_again = np.eye(5, 5)
print(yet_again)
print('-----')

another_id5 = np.eye(5, 5, 0)  # start the 1's in the 0th position (i.e. row 1 and column 1)
print(another_id5)
print('-----')

# What if we want diagonal ones, but not on the main diagonal,
# but starting in the first row and third column rather?
print(np.eye(5, 5, 2))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
-----
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
-----
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
-----
[[0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


## 2. Arrays of random numbers

For simulations it is often helpful to start with an array of random values. Each value might be a starting position or state. Or sometimes you just want to test a piece of code, but not only with 1's and 0's that you have seen till now.

For this it is helpful to create arrays of any shape, filled with random values:

In [3]:
import numpy as np
rnd = np.random.random(size=(4,3))   # random values between 0 (included) and 1 (not included)
print(rnd)

[[0.01368816 0.86677688 0.84657945]
 [0.98786086 0.89295924 0.59952304]
 [0.70638167 0.59402929 0.26870648]
 [0.70122973 0.35996283 0.68491802]]


In [4]:
# Or try a multi-dimensional array
rnd = np.random.random(size=(4, 2, 3))
print(rnd)

[[[0.96403483 0.86524034 0.13552059]
  [0.3328299  0.34656982 0.1088898 ]]

 [[0.10095307 0.1652322  0.6048939 ]
  [0.72723617 0.72142758 0.87748828]]

 [[0.16780978 0.34024089 0.57756603]
  [0.87874104 0.0611315  0.43978818]]

 [[0.89534579 0.67043184 0.71275708]
  [0.27696489 0.41665999 0.87666757]]]


Sometimes we want random integers though, between some ``low``er and upper (``high``) bounds. The random values may include the ``low`` values, but will be till just under the ``high`` value specified.

In [5]:
# Run this code a few times to verify that you get -3, but never +7
rnd = np.random.randint(low=-3, high=7, size=(4, 2, 3))
print(rnd)

[[[-3 -1  1]
  [-3  2 -1]]

 [[ 6 -3  0]
  [ 4  5  5]]

 [[ 2  0  4]
  [-2 -1  3]]

 [[ 2  6  1]
  [ 2  4  6]]]


## 3. Sequences

Vectors containing a sequence, such as ``[0, 1, 2, ... 9]`` or ``[2, 4, 6, 8, ... 12]`` are often used as a starting point for calculations. To create these we use the `numpy.arange()`  and `numpy.linspace()` commands.

*Syntax:*

`numpy.arange(start, stop, step)`

* `start` by default is zero
* `stop` is not inclusive (in other words, NumPy will stop just before this value), and 
* the `step` has a default value of 1.

Try it out below:


In [6]:
np.arange(4)

# we could have also written, but you will agree that this is unnecesary:
np.arange(start=0, stop=4, step=1)

array([0, 1, 2, 3])

In [ ]:
np.arange(start=2, stop=6, step=1)
np.arange(start=2, stop=6)  # leave `step` unspecified if it is just "1"
np.arange(2, 6)             # most common usage: leave all arguments unspecified

In [ ]:
np.arange(start=2, stop=9, step=2)  # jump in steps of 2
np.arange(2, 9, 2)

In [ ]:
np.arange(2, 6, 0.5)  # just in fractional steps

### To try below:

>1. Create a sequence of values starting at -4 and ending just below +4, in steps of 1
>2. Create a sequence of values starting at -2 and ending just below +2, in steps of 0.5. How many elements are the sequence?
>3. Start at +2 and step down in increments of 0.25, until just before -2. How many elements are in the sequence?


In [ ]:
# Step 1:
print(np.arange( ... ))

# Step 2:
uphill = np.arange( -2, 2, 0.5 )
print(uphill)
print(uphill.shape)

# Step 3: going backwards!!
downhill = np.arange( ... )
print(downhill)
print(downhill.shape)


`np.linspace()` is similar to `np.arange()`, but you tell it the length of your sequence, instead of a step size. It returns an array with evenly spaced numbers over the specified interval.  

*Syntax:*

`np.linspace(start, stop, num)`

The `stop` value ***is included*** by default, but it can be removed (type ``np.linspace?`` in your notebook to see how). 
The default value of `num=50`. 

### To try:

>1. Confirm that you indeed get a sequence of 50 values when you do not specify ``num``. Also confirm that the ``stop`` value is the last value in the vector.
>2. Try to get a vector with fewer elements, say 6
>3. Go backwards again: create a sequence where the numbers decrease in value.

In [ ]:
# Step 1:
default = np.linspace(0.0, 4.9)
print(default)
print(default.shape)   # confirm the default length is indeed 50

# Step 2:
print(np.linspace(start=..., stop=..., num= ...))

# Step 3:
print(np.linspace( ... ))

## Matrix from a vector: reshaping

STILL TO COME. use parts of http://nbviewer.jupyter.org/github/engineersCode/EngComp1_offtheground/blob/master/notebooks_en/4_NumPy_Arrays_and_Plotting.ipynb

ADvanced: np.resize

## Next steps

Above, and in prior notebooks we have created vectors, matrices and arrays in all sorts of formats. With ones, zeros, diagonals, random numbers, and sequences of numbers. 

Next it is time to put these to use, and perform calculations on them.