>All content is under Creative Commons Attribution CC-BY 4.0 and all source code is under BSD-3 clause. 
>
>Please reuse, remix, revise, and reshare this content in any way, keeping this notice.
>
>**Viewing this on jupyter.org?** Then this notebook will be read-only. To learn how to interact and actually run the Python code in this notebook, visit our [instruction page about Notebooks](https://yint.org/notebooks).

# Simple elementwise functions and operations on a NumPy array

Once we have created an array - [see the prior notebooks](./) - we are then ready to actually use them for calculations!

Let us consider these calculations:
1. Addition and subtraction
2. Multiplication and division (element-by-element)
3. Square roots and other powers
4. Trigonometric and other functions

## 1. Addition and subtraction

NumPy can add to, or subtract from two arrays with the same shape. We will use array ``A`` and ``B`` in these examples.

In [1]:
import numpy as np

A = np.ones(shape=(5,5))
B = np.ones(shape=(5,5))
print('A = \n{}\n\nB = \n{}'.format(A, B))

A = 
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

B = 
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [2]:
print(A + B)

[[2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]]


The ``+`` operation on two arrays is actually just a convenience. The actual function in NumPy which is being called to do the work is the ``np.add(...)`` function. 

Try this to verify:

In [3]:
print(np.add(A, B))

[[2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]]


Similarly, we have the `-` and `.subtract()` functions that serve the same purpose:

In [4]:
print(A - B)
print(np.subtract(A, B)) # does the same thing as the prior line of code
print(np.add(A, -B))     # and this produces the same result

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


These are element-by-element operations. That means, NumPy performed the operation of addition on each corresponding element in the arrays `A` and `B` and then repeats that entry-by-entry. This is also called element-wise in NumPy's documentation.

NumPy will also allow you take shortcuts. Imagine that you want to subtract the value of 3 from every entry in matrix `A`. You no not first need to create a matrix with the same shape as ``A`` contain the value of 3, and then go subract that. 

**There is a shortcut: **

In [5]:
print(A - 3)  # still does element-by-element calculations

[[-2. -2. -2. -2. -2.]
 [-2. -2. -2. -2. -2.]
 [-2. -2. -2. -2. -2.]
 [-2. -2. -2. -2. -2.]
 [-2. -2. -2. -2. -2.]]


## 2. Multiplication and division (element-by-element)

Multiplication and division can also be done element-by-element. 

In [6]:
import numpy as np
C = np.reshape(np.linspace(1, 25, 25), (5, 5))
print(C)

[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]
 [11. 12. 13. 14. 15.]
 [16. 17. 18. 19. 20.]
 [21. 22. 23. 24. 25.]]


Now go multiply every value in matrix `C` by 2.0 as follows:

In [7]:
doubled = C * 2
print(doubled)

print(np.multiply(C, 2))  # does exactly the same as the prior code

# Also try this:
print(C * 0.0)

[[ 2.  4.  6.  8. 10.]
 [12. 14. 16. 18. 20.]
 [22. 24. 26. 28. 30.]
 [32. 34. 36. 38. 40.]
 [42. 44. 46. 48. 50.]]
[[ 2.  4.  6.  8. 10.]
 [12. 14. 16. 18. 20.]
 [22. 24. 26. 28. 30.]
 [32. 34. 36. 38. 40.]
 [42. 44. 46. 48. 50.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


What happens if you multiply matrix ``C`` by itself, if you want to calculated $C^2$

In [8]:
print(C * C)

[[  1.   4.   9.  16.  25.]
 [ 36.  49.  64.  81. 100.]
 [121. 144. 169. 196. 225.]
 [256. 289. 324. 361. 400.]
 [441. 484. 529. 576. 625.]]


The multiply operator `*` is shorthand for ``numpy.multiply()`` and works on an element-by-element basis. Similarly the `/` operator is shorthand for `numpy.divide()`

In [9]:
print(C / C)
print(np.divide(C, C)) # both give you what you expect - a matrix of 1's

# Advanced: add some code to see what happens if you divide by zero: C/0.0

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


## Square roots and other powers

There are other elementwise operations that can be done on matrices. These often involve raising the individual matrix elements to a certain power, or taking a square root (which is the same as raising a number to the power of $0.5$), or calculating the logarithm.

Let's try it out interactively.

### To try:

> 1. Use the ``**`` operation to raise to a power
> 2. Use the ``.square()`` function 
> 3. Use the ``.power()`` function 
> 4. Use the ``.sqrt()`` function
> 5. Verify that `**(0.5)` gives the same values as the `.sqrt()` function


In [ ]:
# Step 1:
import numpy as np
D = np.reshape(np.linspace(-1, 1, 15), (3, 5))  # create a 3x5 matrix with positive and negative values
print(D**2)
print('-------')

# Step 2
print(np.square(D)) # you should see the same as above
print('-------')

# Step 3
D_squared = np.power(D, 2)
print(D_squared)
print('-------')

# Step 4: remember there are some negative values in D
#         The square root is undefined for negative values (exception for complex values)
print(np.sqrt(D))  
print('-------')

# Step 5: raising something to the power of 0.5 is the same as square rooting
print(np.power(D, 0.5))

## Trigonometric and other functions

A wide variety of mathematical functions are possible. See the full list in the [NumPy documentation](https://docs.scipy.org/doc/numpy/reference/routines.math.html).

You will self-discover these function by running the code below.

### Some questions to try answering below:
>1. The standard trigonometric functions: ``np.sin(...)``, ``np.tan(...)``, etc
>2. Rounding off to the closest integer. Do negative values round up towards zero, or away from zero?
>3. Rounding off to a certain number of ``decimals``; try rounding to 1 decimal place. Are the results what you expect?
>4. Similar to rounding: try the ``np.floor(...)`` and ``np.ceil(...)``: what is the difference between the floor and the ceiling? Hint: read the documentation for [`floor`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.floor.html) and [`ceil`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ceil.html).
>5. Logarithms and exponents are also part of the standard calculations we expect to do with matrices using the ``np.log(...)`` and ``np.exp(...)`` functions. Recall that $\log(\exp(x)) = x$. 


In [11]:
import numpy as np

radians = np.reshape(np.linspace(-2, +2, 16), (4, 4))  # create a 4x4 matrix with positive and negative values
print(radians)
print('-----')

# Step 1
print(np.sin(radians))
print('-----')
print(np.tan(radians))

[[-2.         -1.73333333 -1.46666667 -1.2       ]
 [-0.93333333 -0.66666667 -0.4        -0.13333333]
 [ 0.13333333  0.4         0.66666667  0.93333333]
 [ 1.2         1.46666667  1.73333333  2.        ]]
-----
[[-0.90929743 -0.98681992 -0.9945834  -0.93203909]
 [-0.80360826 -0.6183698  -0.38941834 -0.13293862]
 [ 0.13293862  0.38941834  0.6183698   0.80360826]
 [ 0.93203909  0.9945834   0.98681992  0.90929743]]
-----
[[ 2.18503986  6.09817038 -9.56867673 -2.57215162]
 [-1.35024221 -0.78684289 -0.42279322 -0.13412912]
 [ 0.13412912  0.42279322  0.78684289  1.35024221]
 [ 2.57215162  9.56867673 -6.09817038 -2.18503986]]


In [12]:
# Step 2
print(np.around(radians))  # rounds to the closest integer. Check what happens with negatives!

[[-2. -2. -1. -1.]
 [-1. -1. -0. -0.]
 [ 0.  0.  1.  1.]
 [ 1.  1.  2.  2.]]


In [13]:
# Step 3
print(np.around(radians, decimals=1))  # rounds to the closest 0.1
# Advanced: try this code:  np.around(radians*100, decimals=-2)
# What does it mean to round to a negative number of decimals?

[[-2.  -1.7 -1.5 -1.2]
 [-0.9 -0.7 -0.4 -0.1]
 [ 0.1  0.4  0.7  0.9]
 [ 1.2  1.5  1.7  2. ]]


In [15]:
# Step 4
print(np.floor(radians))  # compare this output to the original matrix
print(np.ceil(radians))   

[[-2. -2. -2. -2.]
 [-1. -1. -1. -1.]
 [ 0.  0.  0.  0.]
 [ 1.  1.  1.  2.]]
[[-2. -1. -1. -1.]
 [-0. -0. -0. -0.]
 [ 1.  1.  1.  1.]
 [ 2.  2.  2.  2.]]


In [16]:
# Step 5
exponent = np.exp(radians)
print(exponent)
print('-----')

recovered = np.log(exponent)
print(recovered)          
print('-----')

# Does "recovered" match the original "radians" matrix? 
# It should: we first took the exponent, then the logarithm.
# This subtraction should be a matrix of all zeros:
print(recovered - radians)

[[0.13533528 0.17669445 0.23069318 0.30119421]
 [0.39324072 0.51341712 0.67032005 0.87517332]
 [1.14263081 1.4918247  1.94773404 2.54297164]
 [3.32011692 4.33476183 5.65948746 7.3890561 ]]
-----
[[-2.         -1.73333333 -1.46666667 -1.2       ]
 [-0.93333333 -0.66666667 -0.4        -0.13333333]
 [ 0.13333333  0.4         0.66666667  0.93333333]
 [ 1.2         1.46666667  1.73333333  2.        ]]
-----
[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  1.11022302e-16 -5.55111512e-17  0.00000000e+00]
 [ 8.32667268e-17 -5.55111512e-17  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]]


The last matrix in your printout above should be all zeros, but is not exactly equal to zero (it is very, very close to zero though).

To test that we can use the ``np.isclose(...)`` function. It is another elementwise function that you can add to your toolbox. It tests if the entries in an array are close to another:

In [17]:
np.isclose(recovered - radians, 0)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [18]:
# There is a function to check if the entries are all `True`
np.allclose(recovered - radians, 0)

True