>All content is released under Creative Commons Attribution [CC-BY 4.0](https://creativecommons.org/licenses/by/4.0/) and all source code is released under a [BSD-3 clause license](https://en.wikipedia.org/wiki/BSD_licenses). Parts of these materials were inspired by https://github.com/engineersCode/EngComp/ (CC-BY 4.0), L.A. Barba, N.C. Clementi.
>
>Please reuse, remix, revise, and reshare this content in any way, keeping this notice.
>
><img style="float: right;" width="150px" src="images/jupyter-logo.png">**Are you viewing this on jupyter.org?** Then this notebook will be read-only. <br>
>See how you can interactively run the code in this notebook by visiting our [instruction page about Notebooks](https://yint.org/notebooks). 

# Functions on the rows or columns of a matrix

In the [prior notebook](./) you learned about elementwise operations. In other words, NumPy performed the mathematicl calculation on every element (entry) in the array.

Sometimes we need calculations the work on every row, or column, of an array. For example:
1. find the maximum value in the entire array (over all rows and all columns)
2. calculate the minimum value in every row (give back a column vector that has the minimum value of every row)
3. calculate the average value of every column (give back a row vector that has the average value of every column)
4. sort the rows, so at the end every column goes from low to high
5. give the cumulative sum going down each column

In this notebook we will talk about matrices, but the operations can be applied to multi-dimensional arrays, with 3, 4, or more dimentions.

## 1. Maximum or minimum value over the entire matrix

You have just received all the data in your matrix, and now you wish to find the largest, or smallest value.


In [22]:
import numpy as np
rnd = np.array([[ 7, 3, 11, 12, 2], [10, 13, 8, 8, 2], [3, 13, 6, 2, 3], [5, 3, 9, 2, 6]])
print('The matrix is:\n {}'.format(rnd))

max_value = np.amax(rnd)
print('The maximum value is {}'.format(max_value))

min_value = np.amin(rnd)
print('The minimum value is {}'.format(min_value))

The matrix is:
 [[ 7  3 11 12  2]
 [10 13  8  8  2]
 [ 3 13  6  2  3]
 [ 5  3  9  2  6]]
The maximum value is 13
The minimum value is 2


The ``np.amax(...)`` and ``np.amin(...)`` functions will work along the entire array: all dimensions, looking at every element.

### Enrichment:

The NumPy library will internally unfold, or flatten the array into a single long vector. Take a look at what that looks like when you use the ``.flatten(...)`` method on the array: ``rnd.flatten()``. It works from column to column, down each row:

```python
print(rnd.flatten())
```
``[ 7  3 11 12  2 10 13  8  8  2  3 13  6  2  3  5  3  9  2  6]``

This is actually how the data is stored internally in the computer's memory.

The reason we point this ``.flatten(...)`` function out is because sometimes knowing what the maximum value is is only half the work. The other half is knowing *where* that maximum value is. For that we have the ``np.argmax(...)`` function.

Try this code:

```python
max_position = np.argmax(rnd)
print('The maximum value is in position {} of the flattened array'.format(max_position))
```

Verify that that is actually the case, using the space below:

In [28]:
# Copy the above code here and run it:



* mean
* sort
* cumulative sum
* max(max(...))
