<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Matrix-multiplication" data-toc-modified-id="Matrix-multiplication-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Matrix multiplication</a></span></li></ul></div>

>All content is released under Creative Commons Attribution [CC-BY 4.0](https://creativecommons.org/licenses/by/4.0/) and all source code is released under a [BSD-3 clause license](https://en.wikipedia.org/wiki/BSD_licenses). 
>
>Please reuse, remix, revise, and reshare this content in any way, keeping this notice.
>
><img style="float: right;" width="150px" src="images/jupyter-logo.png">**Are you viewing this on jupyter.org?** Then this notebook will be read-only. <br>
>See how you can interactively run the code in this notebook by visiting our [instruction page about Notebooks](https://yint.org/notebooks). 

## TODO 
* Transpose introduced
* what happens if the dimensions do not match


We saw earlier examples of matrices; they can be considered like spreadsheets containing rows and observations.

But the real power of matrices come from some of the calculations we can do with them. We have already seen addition and subtraction in a [prior notebook on elementwise functions](./). In that notebook we also saw elementwise multiplication and division.

But there is a special matrix operation, called ***matrix multiplication*** which we will focus on.

### Matrix multiplication

Let us take a look at an example: we multiply one matrix, called $\mathbf{A}$ that has 4 rows and 2 columns, with a second matrix, called $\mathbf{B}$, which contains 2 rows and 3 columns. The result is yet another matrix, we have called it $\mathbf{X}$, and that result has 4 rows and 3 columns.

The value in first row and first column of $\mathbf{A}$ is given by the variable $a_{1,1}$; the value in row 1 and column 2 is $a_{1,2}$. The entry in row $i$ and column $j$ is therefore given by $a_{i,j}$. We use a similar notation for matrix $\mathbf{B}$ and $\mathbf{X}$. 

<img style="float: right;" width="400px" src="images/numpy/Matrix_multiplication_diagram_2.svg.png">
$$\begin{eqnarray}\mathbf{A}\mathbf{B} &=& \mathbf{X}\\
\begin{bmatrix}
{a_{1,1}} & {a_{1,2}} \\
{a_{2,1}} & {a_{2,2}} \\
{a_{3,1}} & {a_{3,2}} \\
{a_{4,1}} & {a_{4,2}} \\
\end{bmatrix}
\begin{bmatrix}
{b_{1,1}} & {b_{1,2}} & {b_{1,3}} \\
{b_{2,1}} & {b_{2,2}} & {b_{2,3}} \\
\end{bmatrix}
&=& \begin{bmatrix}
x_{1,1} & x_{1,2} & x_{1,3} \\
x_{2,1} & x_{2,2} & x_{2,3} \\
x_{3,1} & x_{3,2} & x_{3,3} \\
x_{4,1} & x_{4,2} & x_{4,3} \\
\end{bmatrix}\end{eqnarray}
$$

The values at the intersections marked with circles are:

$\begin{align}
x_{1,2} & = {{a_{1,1}}}{{b_{1,2}}} + {{a_{1,2}}}{{b_{2,2}}} \\
x_{3,3} & = {{a_{3,1}}}{{b_{1,3}}} + {{a_{3,2}}}{{b_{2,3}}}
\end{align}$

Notice how the dimensions are consistent: a vector of 1 row and 2 columns $[{{a_{1,1}}} \,\,\, {{a_{1,2}}}]$ is multiplied element-by-element with $[{{b_{1,2}}}\,\,\, {{b_{2,2}}}]$, and then the multiplied values are added. That process is repeated over and over, until all the values in the new matrix $\mathbf{X}$ is formed.

There is also a pattern: the value that goes into row 1 and column 2 of $\mathbf{X}$ comes from multiplying row 1 of $\mathbf{A}$ and column 2 of $\mathbf{B}$. This form of multiplying the vectors element-by-element and then adding up the result is called the ***dot product***. This explains why the function to do matrix multiplication in NumPy is called ``np.dot(...)``.

Figure credit: [Wikipedia](https://en.wikipedia.org/wiki/Matrix_multiplication#/media/File:Matrix_multiplication_diagram_2.svg)

There is a lot of multiplying and adding happening here; 12 dot products. This is certainly not something you want to do by hand regularly. So ... let's try it with NumPy.

In [23]:
import numpy as np
A = np.array([[8, 7], [6, 5], [4, 3], [2, 1]])
B = np.array([[1, 2, 3], [4, 5, 6]])

print('The values for matrix A = \n{}'.format(A))
print('The values for matrix B = \n{}'.format(B))

X = np.dot(A, B)
print('The values for matrix X = AB is \n{}'.format(X))

# The value of X can also be calculated from:
X = A.dot(B)

print(('The value in position (2,3) of X comes from row 2 '
       'of A [{}] and column 3 of B [{}] which corresponds '
       'to 6*3 + 5*6 = {}').format(A[1,:], B[:,2], 6*3 + 5*6))

The values for matrix A = 
[[8 7]
 [6 5]
 [4 3]
 [2 1]]
The values for matrix B = 
[[1 2 3]
 [4 5 6]]
The values for matrix X = AB is 
[[36 51 66]
 [26 37 48]
 [16 23 30]
 [ 6  9 12]]
The value in position (2,3) of X comes from row 2 of A [[6 5]] and column 3 of B [[3 6]] which corresponds to 6*3 + 5*6 = 48


# The `@` operator for matrix multiplication

Recently ([in 2014](https://www.python.org/dev/peps/pep-0465/)) Python introduced a new operator: `@` specifically defined for matrix multiplication. Depending on if your Python version is up to date, you do not need to write `np.dot(A, B)` anymore, but rather, more compactly: `A @ B` for matrix multiplication.

In [20]:
# Requires a recent Python version 
import numpy as np
A = np.array([[8, 7], [6, 5], [4, 3], [2, 1]])
B = np.array([[1, 2, 3], [4, 5, 6]])

print(('Compact matrix multiplication: A@B = \n{}'').format(A[1,:], B[:,2], 6*3 + 5*6))

array([[36, 51, 66],
       [26, 37, 48],
       [16, 23, 30],
       [ 6,  9, 12]])